[package]
name = "toyc"
version = "0.1.0"
edition = "2024"

[[example]]
name = "tests"

[dependencies]
downcast-rs = "2.0.2"

[dev-dependencies]
insta = {version = "1.46.0", features = ["yaml"]}
xmlwriter = "0.1.0"
