[workspace]
members = ["nockyc"]
resolver = "3"

[workspace.metadata.release]
tag-prefix = "{{crate_name}}/"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
