[package]
name = "toyc"
version = "0.1.0"
edition = "2024"

[[example]]
name = "tests"

[dependencies]
anyhow = "1.0.100"
downcast-rs = "2.0.2"
erased-serde = "0.4.9"
serde = {version ="1.0.228", features=["derive"]}

[dev-dependencies]
insta = {version = "1.46.0", features = ["yaml", "glob"]}
rstest = "0.26.1"
xmlwriter = "0.1.0"
