[[language]]
name = "rust"

[language-server.rust-analyzer.config.imports]
granularity.enforce = true

[language-server.rust-analyzer.config.rustfmt]
overrideCommand = [ "rustfmt", "+nightly", "--unstable-features", "--config", "imports_granularity=Crate,group_imports=StdExternalCrate" ]

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "semantic analysis"
request = "launch"
completion = [ { name = "binary", completion = "filename" }, { name = "source", completion = "filename" } ]
args = { console = "internalConsole", program = "{0}", args = [ "-sem", "{1}" ] }

[[language]]
name = "akyno"
scope = "source.akyno"
injection-regex = "akn|akyno"
file-types = ["akn"]
indent = { tab-width = 4, unit = "    " }
comment-tokens = ["//"]
block-comment-tokens = { start = "/*", end = "*/" }

[[grammar]]
name = "akyno"
source = { path = "/Users/wrenzh/Projects/tree-sitter-akyno" }
